# Generated by Django 3.1.8 on 2021-07-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devboard', '0002_auto_20210624_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
