# Generated by Django 3.1.8 on 2021-07-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devboard', '0003_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
    ]
