# Generated by Django 3.1.8 on 2021-07-07 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devboard', '0004_task_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasknote',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tasknote',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tasknote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasknote',
            name='time_worked',
            field=models.IntegerField(default=0),
        ),
    ]
