# Generated by Django 3.1.8 on 2021-07-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devboard', '0005_auto_20210707_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknote',
            name='date_worked',
            field=models.DateField(default='2021-01-01'),
        ),
    ]
